services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: sbc-tickets
      POSTGRES_USER: userfordevelopment
      POSTGRES_PASSWORD: secretfordevelopment
    ports:
      - "5432:5432"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U userfordevelopment -d sbc-tickets"]
      interval: 5s
      timeout: 5s
      retries: 5